Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    detect: find

# Github's PR width is 120 characters
Layout/LineLength:
  Max: 120
  AllowURI: true

